openapi: "3.0.2"
info:
  title: DB-SYNCER API INTERFACE
  version: "1.0"
  description: DB-SYNCER 서비스 API 정의서 입니다.
servers:
  - url: http://localhost:7962

tags:
  - name: query
    description: 쿼리 동기화
  - name: redis
    description: 레디스 동기화

paths:
  /query/sync:
    post:
      tags: 
        - query
      description: 쿼리 동기화
      summary: 쿼리 동기화
      requestBody:
        content:
          application/json:
            schema:
              properties:
                query:
                  description: 실행할 쿼리 리스트
                  type: array
                  items: 
                    type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    example: 1
                    description: 상태 코드
                  message:
                    type: string
                    example: "success"
                    description: 메시지
                  payload:
                    type: object

  /redis/sync/set:
    post:
      tags: 
        - redis
      description: 레디스 저장 동기화
      summary: 레디스 저장 동기화
      requestBody:
        content:
          application/json:
            schema:
              properties:
                data:
                  description: 실행할 쿼리 리스트
                  type: array
                  items: 
                    type: object
                    properties:
                        key:
                          type: string
                          nullable: false
                          description: 저장할 레디스 key 데이터
                        value:
                          type: string
                          nullable: false
                          description: key에 저장할 value 데이터
                        timeout:
                          type: integer
                          nullable: true
                          description: ttl 데이터
                    
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    example: 1
                    description: 상태 코드
                  message:
                    type: string
                    example: "success"
                    description: 메시지
                  payload:
                    type: object
  /redis/sync/del:
    post:
      tags: 
        - redis
      description: 레디스 삭제 동기화
      summary: 레디스 삭제 동기화
      requestBody:
        content:
          application/json:
            schema:
              properties:
                data:
                  description: 실행할 쿼리 리스트
                  type: array
                  items: 
                    type: object
                    properties:
                        key:
                          type: string
                          nullable: false
                          description: 저장할 레디스 key 데이터
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    example: 1
                    description: 상태 코드
                  message:
                    type: string
                    example: "success"
                    description: 메시지
                  payload:
                    type: object

  ##########################################################################
  # 파일 업로드 (tus 기반)
  ##########################################################################
  /api/tus/file/upload:
    post:
      tags:
        - file
      summary: TUS 파일 업로드 세션 생성
      description: |
        TUS 프로토콜 기반 파일 업로드 세션을 생성
        업로드할 파일의 메타데이터와 크기를 전송하면 업로드 세션 URL을 반환
      parameters:
        - in: header
          name: Upload-Length
          required: true
          schema:
            type: integer
          description: 업로드할 전체 파일 크기 (바이트)
          example: 52428800
        - in: header
          name: Upload-Metadata
          required: false
          schema:
            type: string
          description: 파일 메타데이터 (Base64 인코딩된 key-value 쌍)
          example: "filename dGVzdC5tcDQ=,filetype dmlkZW8vbXA0"
        - in: header
          name: X-Tenant-Id
          required: false
          schema:
            type: string
          description: 테넌트 ID
          example: "1000"
        - in: header
          name: X-Rec-Date
          required: false
          schema:
            type: string
          description: 녹음 날짜 (yyyyMMdd)
          example: "20250106"
        - in: header
          name: X-Rec-Htime
          required: false
          schema:
            type: string
          description: 녹음 시간 (HH)
          example: "14"
        - in: header
          name: X-Rec-Time
          required: false
          schema:
            type: string
          description: 녹음 재생 시간 (hh:mm:ss)
          example: "00:05:30"
        - in: header
          name: X-Ext-No
          required: false
          schema:
            type: string
          description: 내선 번호
          example: "1234"
        - in: header
          name: X-File-Name
          required: false
          schema:
            type: string
          description: 원본 파일명
          example: "recording.mp4"
        - in: header
          name: X-Client-File-Name
          required: false
          schema:
            type: string
          description: 클라이언트 파일명
          example: "recording.mp4"
        - in: header
          name: X-Server-File-Name
          required: false
          schema:
            type: string
          description: 서버 저장 파일명 (고유 파일명)
          example: "1736150400000_abc123def.mp4"
        - in: header
          name: Tus-Resumable
          required: true
          schema:
            type: string
            example: "1.0.0"
          description: TUS 프로토콜 버전
      responses:
        "201":
          description: 업로드 세션 생성 성공
          headers:
            Location:
              description: 업로드를 진행할 고유 URL (PATCH 요청에 사용)
              schema:
                type: string
                example: "/api/tus/file/upload/1736150400000_abc123def"
            Tus-Resumable:
              description: TUS 프로토콜 버전
              schema:
                type: string
                example: "1.0.0"
            Access-Control-Expose-Headers:
              description: CORS 노출 헤더
              schema:
                type: string
                example: "*"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"

    options:
      tags:
        - file
      summary: TUS 프로토콜 지원 정보 조회
      description: |
        서버가 지원하는 TUS 프로토콜 버전 및 확장 기능을 반환
        CORS preflight 요청에도 사용됨
      responses:
        "200":
          description: TUS 프로토콜 정보 반환
          headers:
            Tus-Resumable:
              description: TUS 프로토콜 버전
              schema:
                type: string
                example: "1.0.0"
            Tus-Version:
              description: 지원하는 TUS 버전 목록
              schema:
                type: string
                example: "1.0.0"
            Tus-Extension:
              description: 지원하는 TUS 확장 기능
              schema:
                type: string
                example: "creation,termination,checksum"
            Access-Control-Allow-Methods:
              description: 허용된 HTTP 메서드
              schema:
                type: string
                example: "POST,PATCH,HEAD,OPTIONS"
            Access-Control-Allow-Headers:
              description: 허용된 요청 헤더
              schema:
                type: string
                example: "Upload-Length,Upload-Offset,Tus-Resumable,Upload-Metadata,Content-Type,X-Tenant-Id,X-Rec-Date,X-Rec-Htime,X-Rec-Time,X-Ext-No,X-File-Name,X-Client-File-Name,X-Server-File-Name"
            Access-Control-Expose-Headers:
              description: 노출된 응답 헤더
              schema:
                type: string
                example: "*"

  /api/tus/file/upload/{uploadId}:
    patch:
      tags:
        - file
      summary: TUS 파일 청크 업로드
      description: |
        생성된 업로드 세션에 파일 데이터를 청크 단위로 전송
        Upload-Offset을 통해 이어서 업로드가 가능함
      parameters:
        - in: path
          name: uploadId
          required: true
          schema:
            type: string
          description: 업로드 세션 ID (POST 요청의 Location 헤더에서 반환된 값)
          example: "1736150400000_abc123def"
        - in: header
          name: Upload-Offset
          required: true
          schema:
            type: integer
          description: 현재까지 업로드된 바이트 수
          example: 0
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/offset+octet-stream
          description: TUS 프로토콜 전용 Content-Type
        - in: header
          name: Content-Length
          required: true
          schema:
            type: integer
          description: 현재 전송하는 청크의 크기 (바이트)
          example: 52428800
        - in: header
          name: Tus-Resumable
          required: true
          schema:
            type: string
            example: "1.0.0"
          description: TUS 프로토콜 버전
      requestBody:
        required: true
        content:
          application/offset+octet-stream:
            schema:
              type: string
              format: binary
              description: 파일 청크 데이터 (바이너리)
      responses:
        "200":
          description: 청크 업로드 성공
          headers:
            Upload-Offset:
              description: 현재까지 업로드된 총 바이트 수
              schema:
                type: integer
                example: 52428800
            Tus-Resumable:
              description: TUS 프로토콜 버전
              schema:
                type: string
                example: "1.0.0"
            Access-Control-Expose-Headers:
              description: CORS 노출 헤더
              schema:
                type: string
                example: "*"
        "409":
          description: Upload-Offset 불일치 (충돌 에러)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
        "413":
          description: 전송 용량 초과
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
        "500":
          $ref: "#/components/responses/500"

    head:
      tags:
        - file
      summary: TUS 업로드 상태 조회
      description: |
        현재 업로드 세션의 진행 상태를 확인
        Upload-Offset을 통해 이미 업로드된 바이트 수를 알 수 있음
      parameters:
        - in: path
          name: uploadId
          required: true
          schema:
            type: string
          description: 업로드 세션 ID
          example: "1736150400000_abc123def"
        - in: header
          name: Tus-Resumable
          required: true
          schema:
            type: string
            example: "1.0.0"
          description: TUS 프로토콜 버전
      responses:
        "200":
          description: 업로드 상태 반환
          headers:
            Upload-Offset:
              description: 현재까지 업로드된 바이트 수
              schema:
                type: integer
                example: 26214400
            Upload-Length:
              description: 전체 파일 크기 (바이트)
              schema:
                type: integer
                example: 52428800
            Tus-Resumable:
              description: TUS 프로토콜 버전
              schema:
                type: string
                example: "1.0.0"
            Access-Control-Expose-Headers:
              description: CORS 노출 헤더
              schema:
                type: string
                example: "*"
        "404":
          description: 업로드 세션을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"

    options:
      tags:
        - file
      summary: TUS 업로드 세션 옵션 조회
      description: |
        특정 업로드 세션에 대한 TUS 프로토콜 지원 정보를 반환
        CORS preflight 요청에도 사용됨
      parameters:
        - in: path
          name: uploadId
          required: true
          schema:
            type: string
          description: 업로드 세션 ID
          example: "1736150400000_abc123def"
      responses:
        "200":
          description: TUS 프로토콜 정보 반환
          headers:
            Tus-Resumable:
              description: TUS 프로토콜 버전
              schema:
                type: string
                example: "1.0.0"
            Tus-Version:
              description: 지원하는 TUS 버전 목록
              schema:
                type: string
                example: "1.0.0"
            Access-Control-Allow-Methods:
              description: 허용된 HTTP 메서드
              schema:
                type: string
                example: "POST,PATCH,HEAD,OPTIONS"
            Access-Control-Expose-Headers:
              description: CORS 노출 헤더
              schema:
                type: string
                example: "*"


######################################################################################
######################################################################################

components:
  responses:
    "400":
      description: 파라미터 오류
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"
    "401":
      description: 미인증사용자 혹은 인증실패
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

    "404":
      description: 미인증사용자 혹은 인증실패
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

    "405":
      description: HTTP 메서드 호출 오류 (호출 HTTP 메서드 확인)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

    "500":
      description: 서버측 에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

    default:
      description: 기타  에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

  headers:
    x-request-id:
      description: session identifier
      schema:
        type: string
    x-payload-sign:
      description: message digest
      schema:
        type: string

  schemas:
    ############################
    # Http Error 반환
    ############################
    ErrorResponseBody:
      type: object
      properties:
        status:
          type: integer
          description: 상태코드
        message:
          type: string
          description: 메세지
        payload:
          type: object
          example: null
          nullable: true