openapi: "3.0.2"
info:
  title: DB-SYNCER API INTERFACE
  version: "1.0"
  description: DB-SYNCER 서비스 API 정의서 입니다.
servers:
  - url: http://localhost:7962

tags:
  - name: query
    description: 쿼리 동기화
  - name: redis
    description: 레디스 동기화

paths:
  /query/sync:
    post:
      tags: 
        - query
      description: 쿼리 동기화
      summary: 쿼리 동기화
      requestBody:
        content:
          application/json:
            schema:
              properties:
                query:
                  description: 실행할 쿼리 리스트
                  type: array
                  items: 
                    type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    example: 1
                    description: 상태 코드
                  message:
                    type: string
                    example: "success"
                    description: 메시지
                  payload:
                    type: object

  /redis/sync/set:
    post:
      tags: 
        - redis
      description: 레디스 저장 동기화
      summary: 레디스 저장 동기화
      requestBody:
        content:
          application/json:
            schema:
              properties:
                data:
                  description: 실행할 쿼리 리스트
                  type: array
                  items: 
                    type: object
                    properties:
                        key:
                          type: string
                          nullable: false
                          description: 저장할 레디스 key 데이터
                        value:
                          type: string
                          nullable: false
                          description: key에 저장할 value 데이터
                        timeout:
                          type: integer
                          nullable: true
                          description: ttl 데이터
                    
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    example: 1
                    description: 상태 코드
                  message:
                    type: string
                    example: "success"
                    description: 메시지
                  payload:
                    type: object
  /redis/sync/del:
    post:
      tags: 
        - redis
      description: 레디스 삭제 동기화
      summary: 레디스 삭제 동기화
      requestBody:
        content:
          application/json:
            schema:
              properties:
                data:
                  description: 실행할 쿼리 리스트
                  type: array
                  items: 
                    type: object
                    properties:
                        key:
                          type: string
                          nullable: false
                          description: 저장할 레디스 key 데이터
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: integer
                    example: 1
                    description: 상태 코드
                  message:
                    type: string
                    example: "success"
                    description: 메시지
                  payload:
                    type: object

##########################################################################
# 파일 업로드 (tus 기반)
##########################################################################

  /api/tus/file/upload:
    post:
      tags:
        - file
      summary: TUS 파일 업로드 세션 생성
      description: |
        TUS 프로토콜 기반 파일 업로드 세션을 생성 
        업로드할 파일의 메타데이터와 크기를 전송하면 업로드 세션 URL을 반환
      parameters:
        - in: header
          name: Tus-Resumable
          required: true
          schema:
            type: string
            example: "1.0.0"
          description: TUS 프로토콜 버전
        - in: header
          name: Upload-Length
          required: true
          schema:
            type: integer
            example: 52428800
          description: 업로드할 전체 파일 크기 (바이트)
        - in: header
          name: Upload-Metadata
          required: false
          schema:
            type: string
          description: |
            Base64 인코딩된 key-value 쌍 (예: `"filename dGVzdC5tcDQ="`)
        - in: header
          name: X-Tenant-Id
          schema:
            type: string
          description: 테넌트 ID
        - in: header
          name: X-File-Name
          schema:
            type: string
          description: 클라이언트 원본 파일명
          example: "recording.mp4"
        - in: header
          name: X-Server-File-Name
          schema:
            type: string
          description: 서버 저장용 파일명 (resume 시 동일해야 함)
          example: "1736150400000_abc123def.mp4"
      responses:
        "201":
          description: 업로드 세션 생성 성공
          headers:
            Location:
              schema:
                type: string
                example: "/api/tus/file/upload/1736150400000_abc123def"
            Tus-Resumable:
              schema:
                type: string
                example: "1.0.0"
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: "*"
        "400":
          description: 잘못된 요청 또는 파일 검증 실패
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
        "500":
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"

    patch:
      tags:
        - file
      summary: TUS 파일 업로드 (청크 업로드 및 이어올리기)
      description: |
        기존에 생성된 업로드 세션 URL(`/api/tus/file/upload/{uploadId}`)에  
        파일 데이터를 청크 단위로 전송
        클라이언트는 `Upload-Offset`을 통해 이어서 업로드할 수 있음
      parameters:
        - in: header
          name: Tus-Resumable
          required: true
          schema:
            type: string
            example: "1.0.0"
        - in: header
          name: Upload-Offset
          required: true
          schema:
            type: integer
            example: 0
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: "application/offset+octet-stream"
        - in: header
          name: Content-Length
          required: true
          schema:
            type: integer
            example: 1048576
      requestBody:
        required: true
        content:
          application/offset+octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: 업로드 성공 (또는 이어올리기 성공)
          headers:
            Upload-Offset:
              schema:
                type: integer
                example: 1048576
            Tus-Resumable:
              schema:
                type: string
                example: "1.0.0"
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: "*"
        "400":
          description: 파일 검증 실패
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
        "500":
          $ref: "#/components/responses/500"

    head:
      tags:
        - file
      summary: 업로드 세션 상태 조회
      description: 업로드 세션의 현재 업로드 진행 상태를 확인
      parameters:
        - in: header
          name: Tus-Resumable
          required: true
          schema:
            type: string
            example: "1.0.0"
      responses:
        "200":
          description: 업로드 상태 조회 성공
          headers:
            Upload-Offset:
              schema:
                type: integer
                example: 5242880
            Upload-Length:
              schema:
                type: integer
                example: 10485760
            Tus-Resumable:
              schema:
                type: string
                example: "1.0.0"
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: "*"
        "404":
          description: 업로드 세션을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"

    options:
      tags:
        - file
      summary: CORS Preflight 및 TUS 옵션 조회
      description: 서버가 지원하는 TUS 프로토콜 정보 및 허용된 메서드/헤더 정보를 반환
      responses:
        "200":
          description: 허용된 TUS 설정 반환
          headers:
            Tus-Resumable:
              schema:
                type: string
                example: "1.0.0"
            Tus-Version:
              schema:
                type: string
                example: "1.0.0"
            Tus-Extension:
              schema:
                type: string
                example: "creation,termination,checksum"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: "POST,PATCH,HEAD,OPTIONS"
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: "Upload-Length,Upload-Offset,Tus-Resumable,Upload-Metadata,Content-Type,X-Tenant-Id,X-File-Name,X-Server-File-Name"
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: "*"

######################################################################################
######################################################################################

components:
  responses:
    "400":
      description: 파라미터 오류
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"
    "401":
      description: 미인증사용자 혹은 인증실패
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

    "404":
      description: 미인증사용자 혹은 인증실패
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

    "405":
      description: HTTP 메서드 호출 오류 (호출 HTTP 메서드 확인)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

    "500":
      description: 서버측 에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

    default:
      description: 기타  에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"

  headers:
    x-request-id:
      description: session identifier
      schema:
        type: string
    x-payload-sign:
      description: message digest
      schema:
        type: string

  schemas:
    ############################
    # Http Error 반환
    ############################
    ErrorResponseBody:
      type: object
      properties:
        status:
          type: integer
          description: 상태코드
        message:
          type: string
          description: 메세지
        payload:
          type: object
          example: null
          nullable: true